"use client";
import {FormEvent,useState} from "react";
import type {ConsensusResponse,Provider} from "@/lib/types";
const MODELS=[{id:"openai" as Provider,name:"OpenAI",model:"GPT-4.1 mini",letter:"O",color:"#19966a"},{id:"claude" as Provider,name:"Claude",model:"Sonnet 4",letter:"C",color:"#d17748"},{id:"gemini" as Provider,name:"Gemini",model:"2.5 Flash",letter:"G",color:"#5c78df"}];
const EXAMPLES=["Explain why the sky is blue in a way a 10-year-old can understand.","Design a 30-day learning plan for mastering system design fundamentals.","What are the strongest arguments for and against nuclear energy?"];
const elapsed=(ms:number)=>ms<1000?`${ms} ms`:`${(ms/1000).toFixed(1)} s`;
export default function Home(){
 const [prompt,setPrompt]=useState(EXAMPLES[0]);const [selected,setSelected]=useState<Provider[]>(["openai","claude","gemini"]);const [result,setResult]=useState<ConsensusResponse|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [copied,setCopied]=useState(false);
 const toggle=(id:Provider)=>setSelected(current=>current.includes(id)?(current.length>2?current.filter(x=>x!==id):current):[...current,id]);
 async function run(event:FormEvent){event.preventDefault();if(prompt.trim().length<3)return;setLoading(true);setError("");setResult(null);try{const response=await fetch("/api/consensus",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:prompt.trim(),providers:selected})});const data=await response.json();if(!response.ok)throw new Error(data.error||"The engine could not complete this run.");setResult(data)}catch(e){setError(e instanceof Error?e.message:"Unexpected error")}finally{setLoading(false)}}
 async function copy(){if(!result)return;await navigator.clipboard.writeText(result.synthesis);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 return <main>
  <nav className="nav shell"><a className="brand" href="#top"><span>C</span>Consensus<strong>Lab</strong></a><div className="navlinks"><i/> Engine online <a href="#method">How it works</a><a href="https://github.com/janmejaisingh4/ConsensusLab">GitHub ↗</a></div></nav>
  <section className="hero shell" id="top"><div className="eyebrow">SELF-CONSISTENCY ENGINE <i/></div><h1>One question.<br/><em>Many minds.</em> Better answers.</h1><p>Ask multiple frontier models in parallel, compare their independent reasoning, and synthesize a clearer, more complete response.</p><div className="providers">{MODELS.map(m=><div key={m.id}><span style={{background:m.color}}>{m.letter}</span><b>{m.name}</b><small>{m.model}</small></div>)}</div></section>
  <section className="workspace shell"><form className="composer" onSubmit={run}><div className="head"><label htmlFor="prompt">Ask the panel</label><span>{prompt.length}/2,000</span></div><textarea id="prompt" maxLength={2000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Enter a question that benefits from multiple perspectives…"/><div className="examples">{EXAMPLES.map((x,i)=><button type="button" key={x} onClick={()=>setPrompt(x)} aria-label={`Example ${i+1}`}>0{i+1}</button>)}</div><div className="select"><div><b>Models in this run</b><small>Select at least two</small></div>{MODELS.map(m=><button type="button" aria-pressed={selected.includes(m.id)} className={selected.includes(m.id)?"active":""} key={m.id} onClick={()=>toggle(m.id)}><span style={{background:m.color}}>{m.letter}</span>{m.name}<i>✓</i></button>)}</div><button className="run" disabled={loading||prompt.trim().length<3}>{loading?<><span className="spinner"/> Consulting the panel…</>:<>Generate consensus <span>→</span></>}</button></form>{error&&<div className="error" role="alert">{error}</div>}</section>
  {loading&&<section className="results shell grid">{selected.map(id=>{const m=MODELS.find(x=>x.id===id)!;return <article className="card" key={id}><header><span style={{background:m.color}}>{m.letter}</span><div><b>{m.name}</b><small>Generating response…</small></div></header><div className="skeleton"/><div className="skeleton short"/></article>})}</section>}
  {result&&<section className="results shell"><div className="title"><div><span>RUN COMPLETE · {result.mode.toUpperCase()} MODE</span><h2>Independent responses</h2></div><p>{result.responses.length} models · {elapsed(result.totalMs)}</p></div><div className="grid">{result.responses.map(r=>{const m=MODELS.find(x=>x.id===r.provider)!;return <article className="card" key={r.provider}><header><span style={{background:m.color}}>{m.letter}</span><div><b>{m.name}</b><small>{r.model}</small></div><time>{elapsed(r.latencyMs)}</time></header><p className={r.error?"failed":""}>{r.answer||r.error}</p></article>})}</div><article className="synthesis"><header><div className="spark">✦</div><div><span>CONSENSUS ANSWER</span><h2>Synthesized by {result.evaluator}</h2></div><small>High agreement</small></header><div className="answer">{result.synthesis}</div><footer><span>Built from {result.responses.filter(x=>x.answer).length} independent answers</span><button onClick={copy}>{copied?"Copied!":"Copy answer"}</button></footer></article></section>}
  <section className="method shell" id="method"><div><span>THE METHOD</span><h2>More than majority voting.</h2></div><ol><li><b>01</b><h3>Sample</h3><p>The same prompt goes to multiple models simultaneously.</p></li><li><b>02</b><h3>Compare</h3><p>The evaluator checks accuracy, clarity, and blind spots.</p></li><li><b>03</b><h3>Synthesize</h3><p>The strongest insights become one original answer.</p></li></ol></section>
  <footer className="footer shell"><span>ConsensusLab · GenAI with JS 2026</span><p>Different models. One considered answer.</p></footer>
 </main>
}
